export const ENEMIES = {
  slime_small: {
    ai: 'jump',
    type: 'slime_small',
    bodySize: [12, 8],
    bodyOffset: [10, 24],
    speed: 30,
    level: 1,
    particleTint: 0x00aaaa,
    particleScale: 0.8,
    hp: 2,
    depth: 1,
    damage: 1,
    xp: 2,
    soundKey: 2,
    mass: 10,
  },
  goblin_small: {
    type: 'goblin_small',
    bodySize: [24, 19],
    bodyOffset: [4, 12],
    speed: 40,
    level: 1,
    particleTint: 0x00aa55,
    particleScale: 1.25,
    soundKey: 1,
    hp: 4,
    damage: 2,
    xp: 5,
    mass: 10,
  },
  skull_small: {
    type: 'skull_small',
    ai: 'flying',
    bodySize: [12, 19],
    bodyOffset: [10, 12],
    level: 2,
    speed: 40,
    particleTint: 0xffffff,
    soundKey: 3,
    depth: 3,
    hp: 15,
    damage: 3,
    xp: 10,
    mass: 10,
  },
  knight_small: {
    type: 'knight_small',
    bodySize: [12, 19],
    bodyOffset: [10, 12],
    level: 2,
    speed: 35,
    soundKey: 0,
    hp: 25,
    damage: 3,
    xp: 15,
    mass: 15,
  },
  slime_big: {
    ai: 'jump',
    type: 'slime_big',
    variants: [
      'slime_big',
      'slime_big_bone',
      'slime_big_app',
      'slime_big_bana',
    ],
    bodySize: [28, 18],
    bodyOffset: [3, 13],
    speed: 35,
    level: 3,
    particleTint: 0x00aaaa,
    particleScale: 2,
    range: 25,
    soundKey: 2,
    soundRate: 0.5,
    hp: 10,
    damage: 3,
    xp: 10,
    mass: 15,
  },
  skull_big: {
    type: 'skull_big',
    ai: 'flying',
    bodySize: [12, 19],
    bodyOffset: [10, 12],
    speed: 30,
    level: 3,
    particleTint: 0xffffff,
    soundKey: 3,
    soundRate: 0.5,
    range: 25,
    depth: 3,
    hp: 15,
    damage: 5,
    xp: 5,
    mass: 20,
  },
  goblin_big: {
    type: 'goblin_big',
    bodySize: [24, 28],
    bodyOffset: [4, 4],
    speed: 10,
    soundKey: 4,
    soundRate: 0.75,
    range: 25,
    level: 4,
    hp: 100,
    damage: 5,
    xp: 25,
    mass: 30,
  },
  knight_big: {
    type: 'knight_big',
    bodySize: [24, 28],
    bodyOffset: [4, 4],
    speed: 10,
    soundKey: 5,
    soundRate: 1,
    range: 25,
    level: 5,
    hp: 50,
    damage: 5,
    xp: 100,
    mass: 30,
  },
  slime_jumbo: {
    ai: 'jump',
    type: 'slime_jumbo',
    bodySize: [12, 19],
    bodyOffset: [10, 12],
    speed: 30,
    level: 3,
    scale: 2,
    particleTint: 0x00aaaa,
    range: 35,
    soundKey: 2,
    soundRate: 0.5,
    particleScale: 1.5,
    hp: 50,
    damage: 5,
    xp: 25,
    mass: 30,
  },
  goblin_jumbo: {
    type: 'goblin_jumbo',
    bodySize: [24, 28],
    bodyOffset: [4, 4],
    speed: 6,
    soundKey: 4,
    soundRate: 0.5,
    range: 35,
    level: 4,
    hp: 200,
    scale: 2,
    damage: 5,
    xp: 25,
    mass: 40,
  },
  knight_jumbo: {
    type: 'knight_jumbo',
    bodySize: [24, 28],
    bodyOffset: [4, 4],
    soundKey: 5,
    soundRate: 1,
    speed: 5,
    range: 35,
    level: 5,
    hp: 200,
    scale: 2,
    damage: 5,
    xp: 50,
    mass: 40,
  },
  // eliteKnight: {
  //   type: 'eliteKnight',
  //   bodySize: [12, 19],
  //   bodyOffset: [10, 12],
  //   speed: 20,
  //   hp: 20,
  //   damage: 6,
  //   xp: 25,
  //   mass: 10,
  // },
  // largeEliteKnight: {
  //   type: 'largeEliteKnight',
  //   bodySize: [24, 28],
  //   bodyOffset: [4, 4],
  //   speed: 10,
  //   hp: 100,
  //   damage: 10,
  //   xp: 100,
  //   mass: 10,
  // },
}
