export const ENEMIES = {
  knight: {
    type: 'knight',
    bodySize: [12, 19],
    bodyOffset: [10, 12],
    speed: 30,
    hp: 2,
    damage: 3,
    xp: 5,
    mass: 10,
  },
  eliteKnight: {
    type: 'eliteKnight',
    bodySize: [12, 19],
    bodyOffset: [10, 12],
    speed: 20,
    hp: 20,
    damage: 6,
    xp: 50,
    mass: 10,
  },
  largeKnight: {
    type: 'largeKnight',
    bodySize: [24, 28],
    bodyOffset: [4, 4],
    speed: 10,
    hp: 50,
    damage: 8,
    xp: 100,
    mass: 10,
  },
  goblin: {
    type: 'goblin',
    bodySize: [24, 28],
    bodyOffset: [4, 4],
    speed: 10,
    hp: 50,
    damage: 8,
    xp: 50,
    mass: 10,
  },
  largeEliteKnight: {
    type: 'largeEliteKnight',
    bodySize: [24, 28],
    bodyOffset: [4, 4],
    speed: 10,
    hp: 100,
    damage: 10,
    xp: 150,
    mass: 10,
  },
}
