export const PURCHASES = {
  one: {
    name: 'Magic Missile',
    key: 'one',
    type: 'weapon',
    description: 'Normal medium range attack',
  },
  two: {
    name: 'Orb',
    key: 'two',
    type: 'weapon',
    description: 'Offers protections up close',
  },
  three: {
    name: 'Magic Blade',
    key: 'three',
    type: 'weapon',
    description: 'Powerful melee attack in facing direction.',
  },
  four: {
    name: 'Poison',
    key: 'four',
    type: 'weapon',
    description: 'Automatic short range attack',
  },
  five: {
    name: 'Automagic',
    key: 'five',
    type: 'weapon',
    description: 'Automatic medium range attack',
  },
  six: {
    name: 'Splitter',
    key: 'six',
    type: 'weapon',
    description: 'Powerful explosive medium range',
  },
  seven: {
    name: 'Chain Lightning',
    key: 'seven',
    type: 'weapon',
    description: 'Bouncy all around attack',
  },
  eight: {
    name: 'Bubble Ray',
    key: 'eight',
    type: 'weapon',
    description: 'A stream of rapid but weak damage.',
  },
  //upgrades
  duplicator: {
    name: 'Mirror',
    key: 'duplicator',
    type: 'upgrade',
    description: 'Adds one extra instance of your spells',
  },
  damageBoost: {
    name: 'Damage Boost',
    key: 'damageBoost',
    type: 'upgrade',
    description: 'Adds damage to spells',
  },
  fireDelay: {
    name: 'Cast Speed',
    key: 'fireDelay',
    type: 'upgrade',
    description: 'Cast faster than ever',
  },
  range: {
    name: 'Extra Range',
    key: 'range',
    type: 'upgrade',
    description: 'Spells go further before vanishing',
  },
  bulletSize: {
    name: 'Spell Size',
    key: 'bulletSize',
    type: 'upgrade',
    description: 'Spells are larger',
  },
  maxHP: {
    name: 'Max Health',
    key: 'maxHP',
    type: 'upgrade',
    description: 'Gain more total health',
  },
  healthRegen: {
    name: 'Health Regen',
    key: 'healthRegen',
    type: 'upgrade',
    description: 'Gain health over time',
  },
  moveSpeed: {
    name: 'Move Speed',
    key: 'moveSpeed',
    type: 'upgrade',
    description: 'Move faster',
  },
  pickupRange: {
    name: 'Pickup Range',
    key: 'pickupRange',
    type: 'upgrade',
    description: 'Pick up gems from further away',
  },
  xpRate: {
    name: 'XP Gain',
    key: 'xpRate',
    type: 'upgrade',
    description: 'Gain more XP from gems',
  },
}
