export const PURCHASES = {
  one: {
    name: 'Basic + Shotgun',
    key: 'one',
    type: 'weapon',
    description: 'Normal medium range attack',
  },
  two: {
    name: 'Bible + Orbs',
    key: 'two',
    type: 'weapon',
    description: 'Offers protections up close',
  },
  three: {
    name: 'Whip + Axe',
    key: 'three',
    type: 'weapon',
    description: 'Powerful short range',
  },
  four: {
    name: 'Water + Garlic',
    key: 'four',
    type: 'weapon',
    description: 'Automatic short range attack',
  },
  five: {
    name: 'Wand + Fire',
    key: 'five',
    type: 'weapon',
    description: 'Automatic medium range attack',
  },
  six: {
    name: 'Splitter + Rocket',
    key: 'six',
    type: 'weapon',
    description: 'Powerful explosive medium range',
  },
  seven: {
    name: 'Chain + Bone',
    key: 'seven',
    type: 'weapon',
    description: 'Bouncy all around attack',
  },
  eight: {
    name: 'Bubble + Cross',
    key: 'eight',
    type: 'weapon',
    description: 'Boomerang shots',
  },
  nine: {
    name: 'Tracer',
    key: 'nine',
    type: 'weapon',
    description: 'Piercing attacks',
  },
  //upgrades
  duplicator: {
    name: 'Duplicator',
    key: 'duplicator',
    type: 'upgrade',
    description: 'Adds one bullet to all attacks',
  },
  damageBoost: {
    name: 'Damage Boost',
    key: 'damageBoost',
    type: 'upgrade',
    description: 'Adds damage to all attacks',
  },
  fireDelay: {
    name: 'Attack Speed',
    key: 'fireDelay',
    type: 'upgrade',
    description: 'Attack faster than before',
  },
  range: {
    name: 'Extra Range',
    key: 'range',
    type: 'upgrade',
    description: 'Attacks go further before vanishing',
  },
  // bulletSpeed: {
  //   name: 'Bullet Speed',
  //   key: 'bulletSpeed',
  //   type: 'upgrade',
  //   description: 'Attacks move faster',
  // },
  bulletSize: {
    name: 'Bullet Size',
    key: 'bulletSize',
    type: 'upgrade',
    description: 'Attacks are larger',
  },
  maxHP: {
    name: 'Max Health',
    key: 'maxHP',
    type: 'upgrade',
    description: 'Gain more total hp',
  },
  healthRegen: {
    name: 'Health Regen',
    key: 'healthRegen',
    type: 'upgrade',
    description: 'Slowly gain hp',
  },
  moveSpeed: {
    name: 'Move Speed',
    key: 'moveSpeed',
    type: 'upgrade',
    description: 'Move faster',
  },
  pickupRange: {
    name: 'Pickup Range',
    key: 'pickupRange',
    type: 'upgrade',
    description: 'Pickup xp from further',
  },
  xpRate: {
    name: 'XP Gain',
    key: 'xpRate',
    type: 'upgrade',
    description: 'More xp',
  },
  // armor: {
  //   name: 'Armor',
  //   key: 'armor',
  // type: 'upgrade',
  //   description: 'Reduce incoming damage',
  // },
  // luck: {
  //   name: 'Luck',
  //   key: 'luck',
  // type: 'upgrade',
  //   description: 'More luck',
  // },
}
