export const SPRITES = {
  knight: {
    type: 'enemy',
    name: 'Knight',
    key: 'knight',
    bodySize: [8, 16],
    bodyOffset: [12, 14],
    speed: 30,
    hp: 3,
    damage: 1,
    xp: 5,
  },
  eliteKnight: {
    type: 'enemy',
    name: 'EliteKnight',
    key: 'eliteKnight',
    bodySize: [8, 16],
    bodyOffset: [8, 14],
    speed: 20,
    hp: 50,
    damage: 1,
    xp: 10,
  },
  largeEliteKnight: {
    type: 'enemy',
    name: 'LargeEliteKnight',
    key: 'largeEliteKnight',
    bodySize: [18, 18],
    bodyOffset: [6, 10],
    speed: 10,
    hp: 100,
    damage: 1,
    xp: 20,
  },
  player2: {
    type: 'player',
    name: 'Executioner',
    key: 'player2',
    bodySize: [18, 18],
    bodyOffset: [6, 10],
    speed: 10,
    hp: 100,
  },
  player: {
    type: 'player',
    name: 'Mage',
    key: 'player',
    bodySize: [8, 8],
    bodyOffset: [12, 22],
    speed: 80,
    hp: 100,
  },
}

export const GUNS = {
  // things that shoot toward the pointer
  basic: {
    name: 'basic',
    damage: 1,
    delay: 25,
    speed: 170,
    range: 150,
    frame: 'shot.png',
    size: 1,
    bodySize: 4,
    soundRate: 1.8,
  },
  shotgun: {
    name: 'shotgun',
    damage: 0.66,
    delay: 80,
    offset: 10,
    speed: 140,
    count: 5,
    range: 30,
    health: 3,
    frame: 'shot-shotgun.png',
    size: 3,
    bodySize: 5,
    spread: Math.PI / 3,
    soundRate: 0.5,
  },
  cross: {
    name: 'cross',
    damage: 0.5,
    delay: 50,
    speed: 120,
    range: 200,
    frame: 'shot-cross.png',
    accel: -5,
    size: 2.5,
    health: 10,
    bodySize: 5,
    soundRate: 1.8,
  },
  rocket: {
    name: 'rocket',
    damage: 3,
    delay: 90,
    speed: 60,
    range: 150,
    frame: 'shot-rocket.png',
    size: 2,
    explode: 'rocketExplode',
    bodySize: 4,
    soundRate: 1.8,
  },
  splitter: {
    name: 'splitter',
    damage: 1,
    delay: 30,
    speed: 150,
    range: 150,
    frame: 'shot-splitter.png',
    size: 1,
    explode: 'smallBlast',
    bodySize: 10,
    soundRate: 1.8,
  },
  bubbler: {
    name: 'bubbler',
    damage: 0.1,
    delay: 3,
    count: 1,
    speed: 150,
    range: 150,
    offset: 4,
    spread: 0.25,
    // lower will make it boomerang
    accel: -1,
    randomAngle: true,
    frame: 'shot-bubbler.png',
    size: 1,
    bodySize: 6,
    soundRate: 1.8,
  },
  bone: {
    name: 'bone',
    damage: 1,
    delay: 40,
    speed: 200,
    range: 350,
    frame: 'shot-bone.png',
    size: 1.5,
    health: 10,
    bodySize: 5,
    soundRate: 1.8,
    reacquire: true,
    target: 'randomAngle',
  },
  tracer: {
    name: 'tracer',
    damage: 2,
    delay: 70,
    speed: 150,
    range: 150,
    frame: 'shot-tracer.png',
    size: 1,
    bodySize: 5,
    health: 10,
    soundRate: 1.8,
  },

  // things that aim automatically toward an enemy
  wand: {
    name: 'wand',
    damage: 1,
    delay: 30,
    speed: 50,
    range: 250,
    frame: 'shot-wand.png',
    size: 1,
    bodySize: 5,
    soundRate: 1.8,
    target: 'nearestEnemy',
  },
  fire: {
    name: 'fire',
    damage: 3,
    delay: 120,
    speed: 150,
    range: 250,
    frame: 'shot-fire.png',
    size: 1,
    bodySize: 12,
    soundRate: 1.8,
    target: 'randomEnemy',
  },
  chain: {
    name: 'chain',
    damage: 1,
    delay: 100,
    speed: 250,
    range: 650,
    frame: 'shot-chain.png',
    size: 2,
    health: 99,
    bodySize: 4,
    soundRate: 1.8,
    reacquire: true,
    target: 'nearestEnemy',
  },

  // things that float on/around player
  bible: {
    name: 'bible',
    damage: 1,
    delay: 50,
    speed: 120,
    range: 80,
    frame: 'shot-bible.png',
    size: 2,
    count: 1,
    spread: Math.PI,
    bodySize: 9,
    health: 999,
    lifetime: 50,
    soundRate: 1.8,
    damageOverTime: true,
    target: 'orbit',
  },
  garlic: {
    name: 'garlic',
    damage: 0.05,
    delay: 150,
    speed: 0,
    range: 1,
    frame: 'shot-garlic.png',
    size: 8,
    count: 1,
    maxCount: 1,
    spread: 0,
    alpha: 0.5,
    bodySize: 12,
    health: 99,
    lifetime: 147,
    soundRate: 1.8,
    damageOverTime: true,
    target: 'orbit',
  },

  // things that fire around player
  orbs: {
    name: 'orbs',
    damage: 1,
    delay: 40,
    speed: 40,
    range: 350,
    frame: 'shot-orbs.png',
    size: 3,
    health: 10,
    lifetime: 300,
    bodySize: 10,
    soundRate: 1.8,
    target: 'randomAngle',
  },
  water: {
    name: 'water',
    damage: 1,
    delay: 400,
    speed: 150,
    range: 150,
    frame: 'shot-water.png',
    size: 3,
    bodySize: 10,
    health: 9999,
    lifetime: 400,
    soundRate: 1.8,
    damageOverTime: true,
    target: 'randomPosition',
  },

  // things that fire in front of player
  whip: {
    name: 'whip',
    damage: 1,
    delay: 100,
    speed: 15,
    range: 5,
    frame: 'whip.png',
    size: 1,
    health: 10,
    spread: Math.PI * 2,
    soundRate: 0.5,
    target: 'melee',
    bodyWidth: 45,
    bodyHeight: 18,
    offset: 30,
  },
  axe: {
    name: 'axe',
    damage: 1,
    delay: 30,
    speed: { min: 50, max: 100 },
    speedY: { min: -230, max: -170 },
    range: 250,
    frame: 'shot-axe.png',
    size: 3,
    health: 10,
    bodySize: 5,
    soundRate: 1.8,
    gravity: 300,
    target: 'melee',
  },
  rocketExplode: {
    damage: 1,
    delay: 1,
    speed: 1,
    offset: 1,
    range: 1,
    play: 'explosion',
    size: 2.4,
    bodySize: 20,
    health: 9999,
    lifetime: 30,
    soundRate: 1.8,
  },
  blast: {
    damage: 3,
    delay: 100,
    speed: 60,
    count: 50,
    range: 240,
    frame: 'shot.png',
    size: 3,
    bodySize: 4,
    spread: Math.PI * 2,
    soundRate: 0.5,
  },
  smallBlast: {
    damage: 1,
    delay: 10,
    speed: 80,
    count: 10,
    offset: 1,
    range: 20,
    frame: 'shot-splitter.png',
    size: 0.5,
    bodySize: 10,
    spread: Math.PI * 2,
    soundRate: 0.5,
  },
}

// TODO: define 3 levels for each weapon
export const WEAPONS = {
  one: {
    name: 'one',
    light: 'basic',
    dark: 'shotgun',
    dswitch: 'blast',
    lswitch: null,
    levels: [
      {},
      { count: ['+', 1], damage: ['+', 1] },
      { count: ['+', 2], damage: ['+', 2] },
      { count: ['+', 3], damage: ['+', 3] },
    ],
  },
  // adds extra bullets on switch
  two: {
    name: 'two',
    light: 'bible',
    dark: 'orbs',
    dswitch: 'blast',
    lswitch: null,
    levels: [
      {},
      { damage: ['+', 1] },
      { damage: ['+', 1] },
      { damage: ['+', 1] },
    ],
  },
  // adds axes on switch
  three: {
    name: 'three',
    light: 'whip',
    dark: 'axe',
    dswitch: 'blast',
    lswitch: null,
    levels: [
      {},
      { damage: ['+', 1] },
      { damage: ['+', 1] },
      { damage: ['+', 1] },
    ],
  },
  // adds large aoe on switch
  four: {
    name: 'four',
    light: 'water',
    dark: 'garlic',
    dswitch: 'blast',
    lswitch: null,
    levels: [
      {},
      { damage: ['+', 1] },
      { damage: ['+', 1] },
      { damage: ['+', 1] },
    ],
  },
  // adds extra bullets to switch
  five: {
    name: 'five',
    light: 'wand',
    dark: 'fire',
    dswitch: 'blast',
    lswitch: null,
    levels: [
      {},
      { damage: ['+', 1] },
      { damage: ['+', 1] },
      { damage: ['+', 1] },
    ],
  },
  // explosion on switch
  six: {
    name: 'six',
    light: 'splitter',
    dark: 'rocket',
    dswitch: 'blast',
    lswitch: null,
    levels: [
      {},
      { damage: ['+', 1] },
      { damage: ['+', 1] },
      { damage: ['+', 1] },
    ],
  },
  // adds extra bullets to switch
  seven: {
    name: 'seven',
    light: 'chain',
    dark: 'bone',
    dswitch: 'blast',
    lswitch: null,
    levels: [
      {},
      { damage: ['+', 1] },
      { damage: ['+', 1] },
      { damage: ['+', 1] },
    ],
  },
  // adds boomerang to switch blast
  eight: {
    name: 'eight',
    light: 'bubbler',
    dark: 'cross',
    dswitch: 'blast',
    lswitch: null,
    levels: [
      {},
      { damage: ['+', 1] },
      { damage: ['+', 1] },
      { damage: ['+', 1] },
    ],
  },
  // fireball for dark?
  // adds fireballs on switch
  nine: {
    name: 'nine',
    light: 'tracer',
    dark: 'tracer',
    dswitch: 'blast',
    lswitch: null,
    levels: [
      {},
      { damage: ['+', 1] },
      { damage: ['+', 1] },
      { damage: ['+', 1] },
    ],
  },
}

export const UPGRADES = {
  duplicator: {
    name: 'Duplicator',
    key: 'duplicator',
    type: 'gun',
    levels: [{ count: ['+', 1] }, { count: ['+', 2] }, { count: ['+', 3] }],
  },
  damageBoost: {
    name: 'Damage Boost',
    key: 'damageBoost',
    type: 'gun',
    levels: [
      { damage: ['*', 1.1] },
      { damage: ['*', 1.2] },
      { damage: ['*', 1.3] },
    ],
  },
  fireDelay: {
    name: 'Attack Speed',
    key: 'fireDelay',
    type: 'gun',
    levels: [
      { delay: ['*', 0.9] },
      { delay: ['*', 0.8] },
      { delay: ['*', 0.7] },
    ],
  },
  range: {
    name: 'Extra Range',
    key: 'range',
    type: 'gun',
    levels: [
      { range: ['*', 1.1] },
      { range: ['*', 1.2] },
      { range: ['*', 1.3] },
    ],
  },
  bulletSpeed: {
    name: 'Bullet Speed',
    key: 'bulletSpeed',
    type: 'gun',
    levels: [
      { speed: ['*', 1.1] },
      { speed: ['*', 1.2] },
      { speed: ['*', 1.3] },
    ],
  },
  bulletSize: {
    name: 'Bullet Size',
    key: 'bulletSize',
    type: 'gun',
    levels: [{ size: ['*', 1.1] }, { size: ['*', 1.2] }, { size: ['*', 1.3] }],
  },
  maxHP: {
    name: 'Max Health',
    key: 'maxHP',
    type: 'player',
    levels: [
      { maxHP: ['*', 1.1] },
      { maxHP: ['*', 1.2] },
      { maxHP: ['*', 1.3] },
    ],
  },
  healthRegen: {
    name: 'Health Regen',
    key: 'healthRegen',
    type: 'player',
    levels: [
      { regen: ['+', 1.01] },
      { regen: ['+', 1.02] },
      { regen: ['+', 1.03] },
    ],
  },
  moveSpeed: {
    name: 'Move Speed',
    key: 'moveSpeed',
    type: 'player',
    levels: [{ speed: ['+', 1] }, { speed: ['+', 2] }, { speed: ['+', 3] }],
  },
  pickupRange: {
    name: 'Pickup Range',
    key: 'pickupRange',
    type: 'player',
    levels: [
      { pickupRange: ['+', 1] },
      { pickupRange: ['+', 2] },
      { pickupRange: ['+', 3] },
    ],
  },
  xpRate: {
    name: 'XP Gain',
    key: 'xpRate',
    type: 'player',
    levels: [
      { xpRate: ['*', 1.1] },
      { xpRate: ['*', 1.2] },
      { xpRate: ['*', 1.3] },
    ],
  },
  // luck: {
  //   name: 'Luck',
  //   key: 'luck',
  //   type: 'player',
  //   levels: [
  //     { luck: (d) => d * 1.1 },
  //     { luck: (d) => d * 1.1 },
  //     { luck: (d) => d * 1.1 },
  //   ],
  // },
  // armor: {
  //   name: 'Armor',
  //   key: 'armor',
  //   type: 'player',
  //   levels: [
  //     { armor: (d) => d + 0.1 },
  //     { armor: (d) => d + 0.1 },
  //     { armor: (d) => d + 0.1 },
  //   ],
  // },
}

export const PURCHASES = {
  one: {
    name: 'Basic + Shotgun',
    key: 'one',
    type: 'weapon',
    description: 'Normal medium range attack',
  },
  two: {
    name: 'Bible + Orbs',
    key: 'two',
    type: 'weapon',
    description: 'Offers protections up close',
  },
  three: {
    name: 'Whip + Axe',
    key: 'three',
    type: 'weapon',
    description: 'Powerful short range',
  },
  four: {
    name: 'Water + Garlic',
    key: 'four',
    type: 'weapon',
    description: 'Automatic short range attack',
  },
  five: {
    name: 'Wand + Fire',
    key: 'five',
    type: 'weapon',
    description: 'Automatic medium range attack',
  },
  six: {
    name: 'Splitter + Rocket',
    key: 'six',
    type: 'weapon',
    description: 'Powerful explosive medium range',
  },
  seven: {
    name: 'Chain + Bone',
    key: 'seven',
    type: 'weapon',
    description: 'Bouncy all around attack',
  },
  eight: {
    name: 'Bubble + Cross',
    key: 'eight',
    type: 'weapon',
    description: 'Boomerang shots',
  },
  nine: {
    name: 'Tracer + Fireball',
    key: 'nine',
    type: 'weapon',
    description: 'Piercing attacks',
  },
  //upgrades
  duplicator: {
    name: 'Duplicator',
    key: 'duplicator',
    type: 'upgrade',
    description: 'Adds one bullet to all attacks',
  },
  damageBoost: {
    name: 'Damage Boost',
    key: 'damageBoost',
    type: 'upgrade',
    description: 'Adds damage to all attacks',
  },
  fireDelay: {
    name: 'Attack Speed',
    key: 'fireDelay',
    type: 'upgrade',
    description: 'Attack faster than before',
  },
  range: {
    name: 'Extra Range',
    key: 'range',
    type: 'upgrade',
    description: 'Attacks go further before vanishing',
  },
  bulletSpeed: {
    name: 'Bullet Speed',
    key: 'bulletSpeed',
    type: 'upgrade',
    description: 'Attacks move faster',
  },
  bulletSize: {
    name: 'Bullet Size',
    key: 'bulletSize',
    type: 'upgrade',
    description: 'Attacks are larger',
  },
  maxHP: {
    name: 'Max Health',
    key: 'maxHP',
    type: 'upgrade',
    description: 'Gain more total hp',
  },
  healthRegen: {
    name: 'Health Regen',
    key: 'healthRegen',
    type: 'upgrade',
    description: 'Slowly gain hp',
  },
  moveSpeed: {
    name: 'Move Speed',
    key: 'moveSpeed',
    type: 'upgrade',
    description: 'Move faster',
  },
  pickupRange: {
    name: 'Pickup Range',
    key: 'pickupRange',
    type: 'upgrade',
    description: 'Pickup xp from further',
  },
  xpRate: {
    name: 'XP Gain',
    key: 'xpRate',
    type: 'upgrade',
    description: 'More xp',
  },
  // armor: {
  //   name: 'Armor',
  //   key: 'armor',
  // type: 'upgrade',
  //   description: 'Reduce incoming damage',
  // },
  // luck: {
  //   name: 'Luck',
  //   key: 'luck',
  // type: 'upgrade',
  //   description: 'More luck',
  // },
}

// bosses appear every n minutes
// kill bosses to get new weapons
// level up to get weapon upgrades
