export const SPRITES = {
  knight: {
    type: 'enemy',
    name: 'Knight',
    key: 'knight',
    bodySize: [8, 16],
    bodyOffset: [12, 14],
    speed: 30,
    hp: 3,
    damage: 1,
    xp: 5,
  },
  eliteKnight: {
    type: 'enemy',
    name: 'EliteKnight',
    key: 'eliteKnight',
    bodySize: [8, 16],
    bodyOffset: [8, 14],
    speed: 20,
    hp: 50,
    damage: 1,
    xp: 10,
  },
  largeEliteKnight: {
    type: 'enemy',
    name: 'LargeEliteKnight',
    key: 'largeEliteKnight',
    bodySize: [18, 18],
    bodyOffset: [6, 10],
    speed: 10,
    hp: 100,
    damage: 1,
    xp: 20,
  },
  player2: {
    type: 'player',
    name: 'Executioner',
    key: 'player2',
    bodySize: [18, 18],
    bodyOffset: [6, 10],
    speed: 10,
    hp: 100,
  },
  player: {
    type: 'player',
    name: 'Mage',
    key: 'player',
    bodySize: [8, 8],
    bodyOffset: [12, 22],
    speed: 80,
    hp: 100,
  },
}

export const GUNS = {
  // things that shoot toward the pointer
  basic: {
    damage: 1,
    delay: 25,
    speed: 170,
    range: 150,
    frame: 'shot.png',
    size: 2,
    bodySize: 4,
    soundRate: 1.8,
  },
  shotgun: {
    damage: 0.66,
    delay: 80,
    offset: 10,
    speed: 140,
    count: 5,
    range: 30,
    health: 3,
    frame: 'shot.png',
    size: 3,
    bodySize: 4,
    spread: Math.PI / 3,
    soundRate: 0.5,
  },
  cross: {
    damage: 0.5,
    delay: 50,
    speed: 120,
    range: 200,
    frame: 'shot.png',
    accel: -5,
    size: 3,
    health: 10,
    bodySize: 4,
    soundRate: 1.8,
  },
  rocket: {
    damage: 3,
    delay: 90,
    speed: 60,
    range: 150,
    frame: 'shot.png',
    size: 2,
    explode: 'rocketExplode',
    bodySize: 4,
    soundRate: 1.8,
  },
  splitter: {
    damage: 1,
    delay: 30,
    speed: 150,
    range: 150,
    frame: 'shot.png',
    size: 2,
    explode: 'smallBlast',
    bodySize: 4,
    soundRate: 1.8,
  },
  bubbler: {
    damage: 0.1,
    delay: 3,
    count: 1,
    speed: 150,
    range: 150,
    offset: 4,
    spread: 0.25,
    // lower will make it boomerang
    accel: -1,
    randomAngle: true,
    frame: 'shot.png',
    size: 1,
    bodySize: 4,
    soundRate: 1.8,
  },
  bone: {
    damage: 1,
    delay: 40,
    speed: 200,
    range: 350,
    frame: 'shot.png',
    size: 2,
    health: 10,
    bodySize: 4,
    soundRate: 1.8,
    reacquire: true,
    target: 'randomAngle',
  },
  tracer: {
    damage: 2,
    delay: 70,
    speed: 150,
    range: 150,
    frame: 'shot.png',
    size: 2,
    bodySize: 4,
    health: 10,
    soundRate: 1.8,
  },

  // things that aim automatically toward an enemy
  wand: {
    damage: 1,
    delay: 30,
    speed: 50,
    range: 250,
    frame: 'shot.png',
    size: 2,
    bodySize: 4,
    soundRate: 1.8,
    target: 'nearestEnemy',
  },
  fire: {
    damage: 3,
    delay: 120,
    speed: 150,
    range: 250,
    frame: 'shot.png',
    size: 2,
    bodySize: 4,
    soundRate: 1.8,
    target: 'randomEnemy',
  },
  chain: {
    damage: 1,
    delay: 100,
    speed: 250,
    range: 650,
    frame: 'shot.png',
    size: 2,
    health: 99,
    bodySize: 4,
    soundRate: 1.8,
    reacquire: true,
    target: 'nearestEnemy',
  },

  // things that float on/around player
  bible: {
    damage: 1,
    delay: 50,
    speed: 120,
    range: 80,
    frame: 'shot.png',
    size: 3,
    count: 1,
    spread: Math.PI,
    bodySize: 4,
    health: 999,
    lifetime: 50,
    soundRate: 1.8,
    damageOverTime: true,
    target: 'orbit',
  },
  garlic: {
    damage: 1,
    delay: 150,
    speed: 0,
    range: 1,
    frame: 'shot.png',
    size: 25,
    count: 1,
    spread: 0,
    bodySize: 4,
    health: 999,
    lifetime: 150,
    soundRate: 1.8,
    damageOverTime: true,
    target: 'orbit',
  },

  // things that fire around player
  orbs: {
    damage: 1,
    delay: 40,
    speed: 40,
    range: 350,
    frame: 'shot.png',
    size: 7,
    health: 10,
    lifetime: 300,
    bodySize: 4,
    soundRate: 1.8,
    target: 'randomAngle',
  },
  water: {
    damage: 1,
    delay: 200,
    speed: 150,
    range: 150,
    frame: 'shot.png',
    size: 12,
    bodySize: 4,
    health: 9999,
    lifetime: 200,
    soundRate: 1.8,
    damageOverTime: true,
    target: 'randomPosition',
  },

  // things that fire in front of player
  whip: {
    damage: 1,
    delay: 70,
    speed: 15,
    range: 5,
    frame: 'whip.png',
    size: 1,
    health: 10,
    spread: Math.PI * 2,
    soundRate: 0.5,
    target: 'melee',
    bodyWidth: 45,
    bodyHeight: 18,
    offset: 30,
  },
  axe: {
    damage: 1,
    delay: 30,
    speed: 50,
    speedY: -200,
    range: 250,
    frame: 'shot.png',
    size: 4,
    bodySize: 4,
    soundRate: 1.8,
    gravity: 300,
    target: 'melee',
  },
  rocketExplode: {
    type: 'special',
    damage: 1,
    delay: 1,
    speed: 1,
    offset: 1,
    range: 1,
    play: 'explosion',
    size: 2.4,
    bodySize: 20,
    health: 9999,
    lifetime: 30,
    soundRate: 1.8,
  },
  blast: {
    type: 'special',
    damage: 3,
    delay: 100,
    speed: 60,
    count: 50,
    range: 240,
    frame: 'shot.png',
    size: 3,
    bodySize: 4,
    spread: Math.PI * 2,
    soundRate: 0.5,
  },
  smallBlast: {
    type: 'special',
    damage: 1,
    delay: 10,
    speed: 80,
    count: 10,
    offset: 1,
    range: 20,
    frame: 'shot.png',
    size: 2,
    bodySize: 4,
    spread: Math.PI * 2,
    soundRate: 0.5,
  },
}

export const UPGRADES = {
  upgrade1: { tint: 0xf8961e, name: 'Upgrade', key: 'upgrade' },
  upgrade2: { tint: 0xf3722c, name: 'Upgrade', key: 'upgrade' },
  upgrade3: { tint: 0xf94144, name: 'Upgrade', key: 'upgrade' },
}

// power ups
// add one count to all weapons
// increase damage globally by 10%
// increase fire rate globally by 10%
// increase attack size globally by 10%
// increase xp gain rate by 10%
// increase range of weapons by 10%
// increase speed of weapons by 10%
// increase max health by 10%
// increase luck by 10%
// increase hp gain by .1 ps
// increase armor by 1. armor reduces incoming damage
// increase pickup range
// increase move speed

// make it like hades except
// you can pick 3 weapons, 6 powerups
// you can pick a transform blast power
//

// bosses appear every n minutes
// kill bosses to get new weapons
// level up to get weapon upgrades
